### ISSUE TITLE
列表的数据excel里重复怎么校验啊

### ISSUE THREAD

**Issue by anson88616425** [Mosiki/learning-modules#1]
列表的数据excel里重复怎么校验啊，还有列表的数据自写校验，怎么校验啊？

**Comment by Mosiki** [comment]
> 列表的数据excel里重复怎么校验啊，还有列表的数据自写校验，怎么校验啊？

[参考本文文章](http://nullpointer.pw/easypoi%E5%AF%BC%E5%85%A5Excel%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.html#%E4%B8%83%E3%80%81%E5%AF%BC%E5%85%A5%E5%80%BC%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E4%B9%8BExcel%E9%87%8D%E5%A4%8D%E8%A1%8C%E6%A0%A1%E9%AA%8C)

Excel数据与数据库中值重复校验   和Excel数据中重复值校验都有写，前者是比对数据库，后者通过ThreadLocal实现

**Comment by anson88616425** [comment]
不是我指Collection的excel的数据重复校验，和collection里的自定义校验


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Moski"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 上午9:58
收件人:&nbsp;"Mosiki/learning-modules"<learning-modules@noreply.github.com&gt;;
抄送:&nbsp;"Eric"<278281063@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Mosiki/learning-modules] 列表的数据excel里重复怎么校验啊 (#1)



 
列表的数据excel里重复怎么校验啊，还有列表的数据自写校验，怎么校验啊？
  
参考本文文章
 
Excel数据与数据库中值重复校验   和Excel数据中重复值校验都有写，前者是比对数据库，后者通过ThreadLocal实现

**Comment by Mosiki** [comment]
加群说吧  967808880
