### ISSUE TITLE
demo消费那部分代码存在一部分问题

### ISSUE THREAD

**Issue by dadfengfeng** [Mosiki/learning-modules#5]
demo里消费那部分存在有问题，当connection连接失效时由于while(true)中一直死循环会导致，一直报JedisConnectionException异常，需要在while里面的catch里加一个归还失效连接重新获取连接的逻辑。
`catch (Exception ignored) {
    RedisConnectionUtils.releaseConnection(connection, connectionFactory);
    connection = RedisConnectionUtils.getConnection(connectionFactory);
    // 防止获取 key 达到超时时间抛出 QueryTimeoutException 异常退出
}`

**Comment by Mosiki** [comment]
感谢指正
